language: php

# php version to use for travis' composer & coverage
php:
  - 7.1

services:
  - docker

install:
  - travis_retry make composer install

script:
  - composer validate --no-interaction
  - make ci

after_success:
  - vendor/bin/phpunit --coverage-clover coverage.clover
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

cache:
  directories:
    - $HOME/.composer/cache
